#!/bin/bash
if [[ "$1" == "-u" ]]; then 
    shift
    for file in "$@"; do
        case ${file##*.} in
            "cbr")
                kioclient5 mv "$file" "${file%.*}.rar"
                ;;
            "cbz")
                kioclient5 mv "$file" "${file%.*}.zip"
                ;;
        esac
    done
elif [[ "$1" == "-c" ]]; then 
    shift
    filecounts=$(tempfile)
    for file in "$@"; do
        case ${file##*.} in
            "cbr")
                png=$(rar lb "$file" |grep -ic .png$)
                jpg=$(rar lb "$file" |grep -ic .jpg$)
                jpeg=$(rar lb "$file" |grep -ic .jpeg$)
                gif=$(rar lb "$file" |grep -ic .gif$)
#                 echo "$file": $(rar lb "$file" | tail -2 | head -1 | awk '{ print $2 }') files >> $filecounts
                echo $(basename "$file"): $(( $png + $jpg + $jpeg + $gif )) pages >> $filecounts
                ;;
            "cbz")
                png=$(unzip -Z  "$file" |grep -ic .png$)
                jpg=$(unzip -Z  "$file" |grep -ic .jpg$)
                jpeg=$(unzip -Z  "$file" |grep -ic .jpeg$)
                gif=$(unzip -Z  "$file" |grep -ic .gif$)
#                 echo "$file": $(unzip -Z "$file" | tail -1 | awk '{ print $1 }') files >> $filecounts
                echo $(basename "$file"): $(( $png + $jpg + $jpeg + $gif )) pages >> $filecounts
                ;;
        esac
    done
    kdialog --textbox $filecounts 600 200
    kioclient5 rm $filecounts
elif [[ "$1" == "-j" ]]; then 
    shift
    if [[ -d "$@" ]]; then
        cd "$@"
        ls *.[p,P][n,N][g,G] 2> /dev/null |parallel --eta "convert {} {.}.jpg";
#         ls *.[j,J][p,P][g,G] 2> /dev/null |parallel --eta "mogrify -quality 60% -resize 800\> {}";
        rm -v *.[p,P][n,N][g,G];
        cd ../
        rar a "$@".cbr "$@"
    fi
elif [[ "$1" == "-r" ]]; then 
    shift
    if [[ -d "$@" ]]; then
        cd "$@"
        ls *.[p,P][n,N][g,G] 2> /dev/null |parallel --eta "convert {} {.}.jpg";
        ls *.[j,J][p,P][g,G] 2> /dev/null |parallel --eta "mogrify -quality 60% -resize 800\> {}";
        rm -v *.[p,P][n,N][g,G];
        cd ../
        rar a "$@".cbr "$@"
    fi
else
    for file in "$@"; do
        case ${file##*.} in
            "rar")
                kioclient5 mv "$file" "${file%.*}.cbr"
                ;;
            "zip")
                kioclient5 mv "$file" "${file%.*}.cbz"
                ;;
        esac
    done
fi
